insert into Spitter (username, password, first_name, last_name, email) values ('habuma', 'password', 'Craig Walls', 'King', 'craig@habuma.com');
insert into Spitter (username, password, first_name, last_name, email) values ('mwalls', 'password', 'Michael Walls', 'King', 'mwalls@habuma.com');
insert into Spitter (username, password, first_name, last_name, email) values ('chuck', 'password', 'Chuck Wagon', 'King', 'chuck@habuma.com');
insert into Spitter (username, password, first_name, last_name, email) values ('artnames', 'password', 'Art Names', 'King', 'art@habuma.com');
insert into Spitter (username, password, first_name, last_name, email) values ('cowerling', 'Cowerling', 'Art Names', 'King', 'cowerling@habuma.com');

insert into Spittle (id, message, postedTime) values (1, 'This is a test spittle message', '2012-06-09 22:00:00Z');
insert into Spittle (id, message, postedTime) values (2, 'This is another test spittle message', '2012-06-09 22:10:00Z');
insert into Spittle (id, message, postedTime) values (3, 'This is a third test spittle message', '2012-07-04 23:30:00Z');
insert into Spittle (id, message, postedTime) values (4, 'Hello from Chuck!', '2012-03-25 12:15:00Z');
insert into Spittle (id, message, postedTime) values (5, 'Hello from Art!', '2012-03-25 12:15:00Z');
insert into Spittle (id, message, postedTime) values (6, 'Hello again from Art!', '2012-03-25 12:25:00Z');
insert into Spittle (id, message, postedTime) values (7, 'Hola from Arthur!', '2012-03-25 12:35:00Z');
insert into Spittle (id, message, postedTime) values (8, 'Buenos Dias from Art!', '2012-03-25 12:45:00Z');
insert into Spittle (id, message, postedTime) values (9, 'Ni Hao from Art!', '2012-03-25 12:55:00Z');
insert into Spittle (id, message, postedTime) values (10, 'Guten Tag from Art!', '2012-03-25 13:05:00Z');
insert into Spittle (id, message, postedTime) values (11, 'Konnichi wa from Art!', '2012-03-25 13:15:00Z');
insert into Spittle (id, message, postedTime) values (12, 'Buon giorno from Art!', '2012-03-25 13:25:00Z');
insert into Spittle (id, message, postedTime) values (13, 'Bonjour from Art!', '2012-03-25 13:35:00Z');
insert into Spittle (id, message, postedTime) values (14, 'Aloha from Art!', '2012-03-25 13:45:00Z');
insert into Spittle (id, message, postedTime) values (15, 'God dag from Art!', '2012-03-25 13:55:00Z');
